name: NFS-ShellBot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-ShellBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          git clone https://github.com/vicalloy/telegram-shell-bot
          cd telegram-shell-bot
          pipenv --python 3
          pipenv sync
          pip install delegator-py python-telegram-bot pysocks isort flake8 pre-commit black
          curl $CONFIG_FILE_URL -o settings.py
        env:
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          cd telegram-shell-bot
          python bot.py &
          sleep 300m

      - name: Commit auto run
        run: |
          git config --global user.email "jarbull86@gmail.com"
          git config --global user.name "NFS86"
          git commit --allow-empty -m "NFS-ShellBot Deploy | $(/bin/date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
