name: NFS-ShellBot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-ShellBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: install dependency
        run: |
          sudo apt-get -y update && sudo apt-get -y upgrade && DEBIAN_FRONTEND="noninteractive" \
          sudo apt-get install -y wget git curl python3 python3-pip aria2 qbittorrent-nox \
          tzdata p7zip-full p7zip* xz-utils curl pv jq ffmpeg \
          locales git unzip rtmpdump libmagic-dev libcurl4-openssl-dev \
          libssl-dev libc-ares-dev libsodium-dev libcrypto++-dev \
          libsqlite3-dev libfreeimage-dev libpq-dev libffi-dev apt-utils postgresql-client
          sudo apt-get -y install tzdata
          sudo apt-mark hold tzdata
          sudo ln -snf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
          sudo apt-get -y install pipenv python3 python3-dev build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python3-pip

      - name: clone source
        run: |
          git config --global user.email jarbull86@gmail.com
          git config --global user.name NFS86
          git clone https://github.com/vicalloy/telegram-shell-bot NFS-Shellbot
          cd NFS-Shellbot
          curl $CONFIG_FILE_URL -o settings.py
          pipenv --python 3
          pipenv install -d --skip-lock
        env:
         CONFIG_FILE_URL: ${{secrets.CONFIG}}

      - name: Run Bot..
        run: |
          cd NFS-Shellbot
          pipenv shell
          python3 bot.py &
          sleep 300m

      - name: Commit auto run
        run: |
          git config --local user.email "jarbull86@gmail.com"
          git config --local user.name "NFS86"
          git commit --allow-empty -m "NFS-UserBot Deploy | $(/bin/date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
