name: NFS-ShellBot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-ShellBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - name: Install pipenv 1
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: --python 3

      - name: Install pipenv 2
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d --skip-lock

      - name: Install pipenv 3
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: shell
