name: NFS-ShellBot Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-bot:
    name: NFS-ShellBot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0  # otherwise, you will failed to push refs to dest repo
          persist-credentials: false  # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token

      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          git clone https://github.com/vicalloy/telegram-shell-bot
          cd telegram-shell-bot
          pipenv --python 3
          pipenv sync
          Pipenv install -d Pipfile.lock
          curl $CONFIG_FILE_URL -o settings.py
          python bot.py
        env:
         CONFIG_FILE_URL: ${{secrets.CONFIG}}
